version: 0.2

phases:
   install:
    runtime-versions:
      java: openjdk8
   build:
     commands:
     - echo Entered the build phase.......
     - mvn clean package
     post_build:
        commands:
        - echo Build completed successfully
artifacts:
  files:
  - target/spring-boot-test-json-1.0.jar
   discard-paths:yes		