version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Entered the build phase.......
      - mvn clean package
      - echo "Built JAR file is located at: $(find . -name '*.jar')"
  post_build:
    commands:
      - echo Build completed successfully

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
